# Generated by Django 5.1.7 on 2025-03-30 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_maintenancerequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancerequest',
            options={'ordering': ['-request_date'], 'verbose_name': 'Maintenance Request', 'verbose_name_plural': 'Maintenance Requests'},
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='maintenance_attachments/'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='resolved_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
