# Generated by Django 5.2 on 2025-05-09 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_leaseagreement'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalLeaseAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease_text', models.TextField()),
                ('tenant_signed', models.BooleanField(default=False)),
                ('tenant_signature', models.TextField(blank=True, null=True)),
                ('tenant_signed_at', models.DateTimeField(blank=True, null=True)),
                ('homeowner_signed', models.BooleanField(default=False)),
                ('homeowner_signature', models.TextField(blank=True, null=True)),
                ('homeowner_signed_at', models.DateTimeField(blank=True, null=True)),
                ('lease_document', models.FileField(blank=True, null=True, upload_to='rental_lease_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rental', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rental_lease_agreement', to='user.rental')),
                ('rental_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rental_lease_agreement', to='user.rentalrequest')),
            ],
        ),
    ]
