# Generated by Django 5.2 on 2025-05-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rentalleaseagreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalrequest',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
