# Generated by Django 5.2 on 2025-05-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rentalrequest_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalleaseagreement',
            name='tenant_id_back',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_ids/'),
        ),
        migrations.AddField(
            model_name='rentalleaseagreement',
            name='tenant_id_front',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_ids/'),
        ),
    ]
