"""
Django settings for PayTrack project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v5u@pem)9oq5&$6-cwe)+a#%l-!!9zcr-#+kui!)a=rze&dr6t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
        'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'user',
    'notification',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'PayTrack.urls'
AUTH_USER_MODEL = 'user.CustomUser'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]

LOGIN_REDIRECT_URL = '/dashboard/'  # Redirect here after login

WSGI_APPLICATION = 'PayTrack.wsgi.application'




# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

import ssl
import certifi

EMAIL_USE_TLS = True  # or EMAIL_USE_SSL = True, depending on your SMTP server
EMAIL_SSL_CONTEXT = ssl.create_default_context(cafile=certifi.where())


# Email Backend for Production
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = 'evenntaevent@gmail.com'
EMAIL_HOST_PASSWORD = 'eamj xsmh pnws ljof'
  # Use App Password if 2FA is enabl
  #ed
EMAIL_SSL_CONTEXT = ssl._create_unverified_context()


SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 600  # Session expires in 10 minutes
SESSION_SAVE_EVERY_REQUEST = True


STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"



JAZZMIN_SETTINGS = {
    # Window title (Defaults to current_admin_site.site_title if None)
    "site_title": "PayTrack Admin",

    # Title on the login screen (19 chars max)
    "site_header": "PayTrack",

    # Title on the brand (19 chars max)
    "site_brand": "PayTrack",

    # Logo for branding (must be in static files)
    "site_logo": "images/logo.png",

    # Logo for login form (Defaults to site_logo if None)
    "login_logo": "images/logo.png",

    # Logo for login form in dark themes
    "login_logo_dark": "images/logo.png",

    # CSS classes applied to the logo
    "site_logo_classes": "img-circle",

    # Relative path to a favicon (32x32 px recommended)
    "site_icon": "images/logo.png",

    # Welcome message on login screen
    "welcome_sign": "Welcome to PayTrack - Property Management",

    # Copyright footer text
    "copyright": "PayTrack Inc. © 2025",

  

    # User profile avatar field (ImageField/URLField on CustomUser model)
    "user_avatar": "profile_picture",

    ############
    # Top Menu #
    ############
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "PayTrack Website", "url": "http://127.0.0.1:8000/", "new_window": True},
        {"model": "user.CustomUser"},
        {"model": "property.Property"},
        {"model": "transaction.Transaction"},
       
    ],

    #############
    # User Menu #
    #############
    "usermenu_links": [
        {"name": "Support", "url": "https://support.paytrack.com", "new_window": True},
        {"name": "Profile", "url": "/admin/user/customuser/", "permissions": ["user.view_customuser"]},
        {"model": "auth.user"}
    ],

    #############
    # Side Menu #
    #############
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": [
        "user",
        "property",
        "transaction",
    ],

    # Custom links for side menu
    "custom_links": {
        "transaction": [
            {
                "name": "Generate Reports",
                "url": "generate_reports",
                "icon": "fas fa-file-invoice",
                "permissions": ["transaction.view_transaction"]
            },
            {
                "name": "Payment Overview",
                "url": "payment_overview",
                "icon": "fas fa-money-check-alt",
                "permissions": ["transaction.view_transaction"]
            },
        ]
    },

    # Custom icons for models and apps
    "icons": {
        "auth": "fas fa-users-cog",
        "user.CustomUser": "fas fa-user",
        "property.Property": "fas fa-building",
        "transaction.Transaction": "fas fa-money-bill-wave",
        "auth.Group": "fas fa-users",
    },

    # Default icons if none are specified
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    #################
    # Related Modal #
    #################
    "related_modal_active": True,

    #############
    # UI Tweaks #
    #############
    "custom_css": "paytrack/css/custom_admin.css",
    "custom_js": "paytrack/js/custom_admin.js",
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,

    ###############
    # Change View #
    ###############
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "user.CustomUser": "collapsible",
        "property.Property": "vertical_tabs",
    },

    # Language dropdown in admin
}